name: CI - Check Set-Up, Build & Test

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

    workflow_dispatch:

jobs:
    check:
        runs-on: ubuntu-latest
        env:
            # Fix version to prevent cache misses with nightly changes
            NODE_JS: 16.19.1

        steps:
            - uses: actions/checkout@v3

            - name: Install Dependencies
              run: |
                  sudo apt-get update &&
                  sudo apt-get install -y protobuf-compiler &&
                  sudo rm -rf /var/lib/apt/lists/*

            - name: Install Rust
              uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: stable

            - name: Rust Cache
              uses: Swatinem/rust-cache@988c164c3d0e93c4dbab36aaf5bbeb77425b2894 # v2.4.0
              with:
                  cache-on-failure: true
                  cache-all-crates: true

            - name: Install Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: ${{ env.NODE_JS }}

            - name: Install E2E Tests Dependencies
              run: |
                  yarn install

            - name: Check Rust formatting
              run: |
                  cargo fmt --check

            - name: Output versions
              run: |
                  cargo -vV

            - name: Check building
              run: |
                  cargo check

            - name: Run tests
              run: |
                  cargo test

            - name: Check clippy linting
              run: |
                  cargo clippy --all-features

            - name: Check JS formatting with Prettier
              run: |
                  yarn prettier --check .

            - name: Check JS formatting with ESLint
              run: |
                  yarn run eslint .
